
// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview An AI flow for a portfolio chatbot.
 *
 * - chatbotFlow - A function that handles the chatbot conversation.
 * - ChatbotInput - The input type for the chatbotFlow function.
 * - ChatbotOutput - The return type for the chatbotFlow function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const MessageSchema = z.object({
  role: z.enum(['user', 'model']),
  content: z.string(),
});

const ChatbotInputSchema = z.object({
  history: z.array(MessageSchema).describe('The conversation history.'),
});
export type ChatbotInput = z.infer<typeof ChatbotInputSchema>;

const ChatbotOutputSchema = z.object({
  content: z.string().describe("The chatbot's response."),
});
export type ChatbotOutput = z.infer<typeof ChatbotOutputSchema>;

export async function chatbotFlow(input: ChatbotInput): Promise<ChatbotOutput> {
  const {history} = input;

  const systemPrompt = `You are a friendly and helpful AI assistant for Kunal's developer portfolio.
Your goal is to answer questions about Kunal's skills, experience, and projects in a conversational manner.
Keep your answers concise and engaging.

Here's some information about Kunal:
- Skills: React, Next.js, TypeScript, JavaScript (ES6+), HTML5, CSS3, Tailwind CSS, ShadCN UI, Git, GitHub, Figma, Adobe XD, Firebase, Node.js, Genkit.
- Experience: Frontend Developer Intern at Google, Software Engineer Intern at Microsoft. He has worked on Google Search and the Microsoft Azure portal.
- Projects: A portfolio with an AI JD analyzer, a Spotify clone, an E-commerce platform, a Task Management App, and an AI Chatbot (that's you!).
- Education: Bachelor of Technology in Computer Science from IIT Bombay.
- Contact: Users can get in touch via the contact form on the website.

If you don't know the answer to something, say so politely.

Analyze the conversation history and provide a relevant and helpful response.
`;

  const {output} = await ai.generate({
    history,
    system: systemPrompt,
  });

  const responseText = output?.text;
  if (!responseText) {
    return {content: "I'm sorry, I'm having trouble responding right now. Please try again in a moment."};
  }

  return {content: responseText};
}
