// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent that generates an inspiring quote.
 *
 * - generateQuote - A function that returns a quote.
 * - Quote - The return type for the generateQuote function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const QuoteSchema = z.object({
  quote: z.string().describe('The text of the quote.'),
  author: z.string().describe('The author of the quote.'),
});
export type Quote = z.infer<typeof QuoteSchema>;

export async function generateQuote(): Promise<Quote> {
  return generateQuoteFlow();
}

const prompt = ai.definePrompt({
  name: 'quotePrompt',
  output: {schema: QuoteSchema},
  prompt: `Generate a short, inspiring quote suitable for a software developer portfolio. The quote should be about technology, creativity, programming, or innovation. Also provide the author of the quote. If the author is unknown, attribute it to "Anonymous".`,
});

const generateQuoteFlow = ai.defineFlow(
  {
    name: 'generateQuoteFlow',
    outputSchema: QuoteSchema,
  },
  async () => {
    const {output} = await prompt();
    return output!;
  }
);
