// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent that suggests relevant skills based on project descriptions.
 *
 * - suggestSkills - A function that suggests skills based on project descriptions.
 * - SuggestSkillsInput - The input type for the suggestSkills function.
 * - SuggestSkillsOutput - The return type for the suggestSkills function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestSkillsInputSchema = z.object({
  projectDescriptions: z
    .string()
    .describe('A detailed description of the projects the developer has worked on.'),
});
export type SuggestSkillsInput = z.infer<typeof SuggestSkillsInputSchema>;

const SuggestSkillsOutputSchema = z.object({
  suggestedSkills: z
    .array(z.string())
    .describe('An array of skills suggested based on the project descriptions.'),
});
export type SuggestSkillsOutput = z.infer<typeof SuggestSkillsOutputSchema>;

export async function suggestSkills(input: SuggestSkillsInput): Promise<SuggestSkillsOutput> {
  return suggestSkillsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestSkillsPrompt',
  input: {schema: SuggestSkillsInputSchema},
  output: {schema: SuggestSkillsOutputSchema},
  prompt: `You are an AI assistant that helps developers identify relevant skills to list on their portfolio based on their project descriptions.

  Analyze the following project descriptions and suggest a list of skills that the developer should highlight in their portfolio. Be specific and focus on technical skills related to software development, such as programming languages, frameworks, tools, and methodologies.

  Project Descriptions: {{{projectDescriptions}}}

  Skills:`,
});

const suggestSkillsFlow = ai.defineFlow(
  {
    name: 'suggestSkillsFlow',
    inputSchema: SuggestSkillsInputSchema,
    outputSchema: SuggestSkillsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
