export const technologies = [
  "React",
  "Next.js",
  "TypeScript",
  "JavaScript",
  "HTML5",
  "CSS3",
  "Tailwind CSS",
  "ShadCN UI",
  "Firebase",
  "Node.js",
  "Vercel",
];

export const projects = [
  {
    id: 1,
    title: "DevPortfolio",
    description: "A modern, interactive, and AI-powered portfolio for developers. Features a JD analyzer to match skills with job descriptions. Built with Next.js, Tailwind CSS, and Genkit.",
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "code editor",
    liveUrl: "#",
    repoUrl: "#",
    tags: ["Next.js", "React", "Tailwind CSS", "Genkit", "TypeScript"],
  },
  {
    id: 2,
    title: "Spotify Clone",
    description: "A web app for visualizing personalized Spotify data. View your top artists, top tracks, recently played tracks, and detailed audio information about each track.",
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "music player interface",
    liveUrl: "#",
    repoUrl: "#",
    tags: ["React", "Next.js", "Tailwind CSS", "Spotify API"],
  },
  {
    id: 3,
    title: "E-commerce Platform",
    description: "A full-stack e-commerce solution with product listings, a shopping cart, and a checkout process. Integrated with Stripe for payments. Backend built with Node.js and Firebase.",
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "online shopping",
    liveUrl: "#",
    repoUrl: "#",
    tags: ["React", "Node.js", "Firebase", "Stripe API", "Tailwind CSS"],
  },
   {
    id: 4,
    title: "Task Management App",
    description: "A Kanban-style task management application with drag-and-drop functionality to organize tasks. User authentication and real-time database updates with Firebase.",
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "kanban board software",
    liveUrl: "#",
    repoUrl: "#",
    tags: ["React", "Firebase", "Tailwind CSS", "React-beautiful-dnd"],
  },
   {
    id: 5,
    title: "AI Chatbot",
    description: "An intelligent chatbot built with Genkit and React. It can answer questions, provide information, and engage in natural-sounding conversations.",
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "chatbot conversation",
    liveUrl: "#",
    repoUrl: "#",
    tags: ["React", "Genkit", "Firebase", "Tailwind CSS"],
  },
];
