// This file is generated by Firebase Studio.
'use server';

import {z} from 'zod';

const formSchema = z.object({
  name: z.string().min(2, {message: 'Name must be at least 2 characters.'}),
  email: z.string().email({message: 'Please enter a valid email address.'}),
  message: z.string().min(10, {message: 'Message must be at least 10 characters.'}),
});

type FormValues = z.infer<typeof formSchema>;

export async function handleFormSubmit(data: FormValues) {
  // In a real app, you would integrate with an email service like Resend or SendGrid.
  console.log('Form submitted:', data);
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 1000));
  return {success: true, message: 'Your message has been sent successfully!'};
}